### ISSUE TITLE
some error open"https://seed-rs.org/" with firefox

### ISSUE THREAD

**Issue by rooat** [seed-rs/seed-rs.org#12] opened 2019-12-17 08:45 UTC
"Unexpected node type found from raw html"

**Comment by David-OConnor** [comment] 2019-12-18 04:25
Could you please provide more details? Ie what part of the page (The landing page?) What version of Firefox? Is this in the F12 terminal? Does the page render correctly?

**Comment by MartinKavik** [comment] 2020-01-02 15:56
Can't reproduce, missing details, 16 days without answer - closing.
@rooat We'll reopen it once you provide more info.

**Closed by MartinKavik** 2020-01-02 15:56 UTC
